#ifndef TRIANGLE_TIPE_H_ 
#define TRIANGLE_TIPE_H_ 

enum TriangleTipe{
    TRINAGLE_TIPE_EQUILATERAL,
    TRINAGLE_TIPE_ISOSCELES_RIGHT_ANGLED,
    TRINAGLE_TIPE_ISOSCELES,
    TRINAGLE_TIPE_RIGHT_ANGLED,
    TRINAGLE_TIPE_ARBITRARY
    };

#endif  // TRIANGLE_TIPE_H_ 