#ifndef TRIANGLE_TYPE_H_ 
#define TRIANGLE_TYPE_H_ 

enum TriangleType{
    TRINAGLE_TYPE_EQUILATERAL,
    TRINAGLE_TYPE_ISOSCELES_RIGHT_ANGLED,
    TRINAGLE_TYPE_ISOSCELES,
    TRINAGLE_TYPE_RIGHT_ANGLED,
    TRINAGLE_TYPE_ARBITRARY
    };

#endif  // TRIANGLE_TYPE_H_ 